name: deepdream_hackathon
dependencies:
    - python==3.7.4
    - matplotlib==3.1.1
    - pillow==6.1.0
    - scipy==1.3.1
    - pip==19.2.3
    - pip:
        - opencv-python==4.1.1.26
        - tensorflow==1.14.0
